# This is a basic workflow to help you get started with Actions
name: deploy on commit

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # TODO: have the queue deployed as part of CI/CD.  Currently it is manual.
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: install build test
        run: |
          yarn install
          yarn build
          yarn test
      - id: actual-deploy
        uses: google-github-actions/deploy-cloud-functions@v0.2.0
        with:
          name: example-easypost-webhook-processor
          runtime: nodejs10
          credentials: ${{ secrets.GCP_SA_KEY }}
          entry_point: easypostProcessor
          timeout: 240
      - name: Output completion
        run: |
          echo Deploy completed
